# Generated by Django 3.2.12 on 2022-04-25 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0002_auto_20220422_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompiler',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='Featured on homepage'),
        ),
    ]
