# Generated by Django 4.0.6 on 2022-07-08 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_decompiler_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompiler',
            name='url',
            field=models.URLField(default='https://dogbolt.org/', max_length=255),
            preserve_default=False,
        ),
    ]
