# Generated by Django 3.2.12 on 2022-07-09 02:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_decompiler_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompiler',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
