# Generated by Django 3.2.12 on 2022-07-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0007_decompilationrequest_last_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binary',
            name='featured_name',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
