# Generated by Django 3.2.12 on 2022-07-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0008_alter_binary_featured_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompiler',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured on homepage'),
        ),
    ]
