# Generated by Django 3.2.15 on 2023-01-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0009_alter_decompiler_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binary',
            options={'verbose_name_plural': 'binaries'},
        ),
        migrations.RemoveField(
            model_name='decompilationrequest',
            name='completed',
        ),
    ]
