# Generated by Django 3.2.16 on 2023-01-19 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0010_auto_20230105_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='decompilationrequest',
            name='completed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
