# Generated by Django 3.2.16 on 2023-01-19 23:01

from django.db import migrations


def populate_completed(apps, schema_editor):
    DecompilationRequest = apps.get_model('explorer', 'decompilationrequest')
    DecompilationRequest.objects.exclude(decompilation=None).update(completed=True)

class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0011_decompilationrequest_completed'),
    ]

    operations = [
        migrations.RunPython(
            code=populate_completed,
        ),
    ]
