# Generated by Django 3.2.19 on 2023-11-20 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0012_auto_20230119_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompilationrequest',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
    ]
