# Generated by Django 3.2.19 on 2023-11-20 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0013_alter_decompilationrequest_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decompilationrequest',
            options={'ordering': ['created']},
        ),
    ]
