# Generated by Django 3.2.19 on 2023-11-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0014_alter_decompilationrequest_options'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='decompilationrequest',
            index_together={('created', 'completed')},
        ),
    ]
