# Generated by Django 3.2.19 on 2023-11-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0016_alter_decompilationrequest_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decompilation',
            name='request',
        ),
        migrations.AlterIndexTogether(
            name='decompilationrequest',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='decompilationrequest',
            name='completed',
        ),
    ]
