# Generated by Django 3.2.19 on 2023-11-28 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0017_auto_20231120_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decompilationrequest',
            name='decompiler',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='decompilation_requests', to='explorer.decompiler'),
        ),
    ]
