# Generated by Django 3.2.19 on 2023-11-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0018_alter_decompilationrequest_decompiler'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='decompiler',
            constraint=models.UniqueConstraint(fields=('name', 'version', 'revision', 'url'), name='unique_decompiler_info'),
        ),
    ]
