version: '3.8'

x-decompiler:
    &default-decompiler-options
        extra_hosts:
            - "${AWS_S3_ENDPOINT_HOST}:${AWS_S3_ENDPOINT_IP}"


services:
    explorer:
        environment:
            - DJANGO_FILE_STORAGE=decompiler_explorer.storage.CustomS3Storage
            - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME:?S3 bucket name unset}
            - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:?S3 endpoint url unset}
            - AWS_S3_REGION_NAME=${AWS_S3_REGION_NAME:?S3 region name unset}
        secrets:
            - s3_access_key_id
            - s3_secret_access_key

    binja:
        <<: *default-decompiler-options
    ghidra:
        <<: *default-decompiler-options
    angr:
        <<: *default-decompiler-options
    snowman:
        <<: *default-decompiler-options
    retdec:
        <<: *default-decompiler-options
    recstudio:
        <<: *default-decompiler-options
    boomerang:
        <<: *default-decompiler-options
    reko:
        <<: *default-decompiler-options
    hexrays:
        <<: *default-decompiler-options
    dewolf:
        <<: *default-decompiler-options
    relyze:
        <<: *default-decompiler-options
    revng:
        <<: *default-decompiler-options


secrets:
    s3_access_key_id:
        file: ./secrets/s3_access_key_id
    s3_secret_access_key:
        file: ./secrets/s3_secret_access_key
